apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dtag-dev
  name: react-loginform
  labels:
    app: react-loginform
    version: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-loginform
      version: dev
  template:
    metadata:
      name: react-loginform
      labels:
        app: react-loginform
        version: dev
    spec:
      containers:
      - name: react-loginform
        image: mohammadaszadali/react-login-form:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  namespace: dtag-dev
  name: loginform-react
  labels:
    app: loginform-react
    version: dev
spec:
  type: LoadBalancer
  ports:
  - targetPort: 3000
    port: 3000
  selector:
    app: react-loginform
    version: dev
